In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving energydata_complete.csv to energydata_complete.csv

In [53]:
df = pd.read_csv('energydata_complete.csv')

In [54]:
feature_weights = model.coef_

print("Feature Weights:")
for feature, weight in zip(X.columns, feature_weights):
    print(feature, ":", weight)

Feature Weights:
T1 : -3.510724777948495
RH_1 : 592.2948618273451
T2 : -252.71037300355457
RH_2 : -488.6668047221957
T3 : 310.97103712182707
RH_3 : 102.77165243747163
T4 : 31.00966845325146
RH_4 : 28.232781274228053
T5 : -16.752821773132705
RH_5 : 17.126193618103017
T6 : 252.97465248716392
RH_6 : 40.712057703076475
T7 : 11.041090735099667
RH_7 : -47.73659197636444
T8 : 109.13469841073217
RH_8 : -168.62716102144046
T9 : -203.2366271188889
RH_9 : -42.586338779999
T_out : -344.3898448991904
Press_mm_hg : 7.318079229559398
RH_out : -83.1075989043834
Windspeed : 31.22594824232032
Visibility : 13.168071605187635
Tdewpoint : 126.00077633919382
rv1 : 0.8240050024984789
rv2 : 0.8240050024995678

In [5]:
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [7]:
T2 = df['T2']
T6 = df['T6']

In [9]:
X = df['T2'].values.reshape(-1, 1)
y = df['T6'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)


r2 = r2_score(y_test, y_pred)

print(f"R-squared value: {r2:.2f}")

R-squared value: 0.64

In [27]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [28]:
columns_to_remove = ["date", "lights"]
df = df.drop(columns=columns_to_remove)

KeyError: ignored

In [13]:
df

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,60,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,50,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,50,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,60,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,100,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,23.200000,...,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,90,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,45.590000,23.230000,...,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,270,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,23.230000,...,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,420,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,23.200000,...,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,430,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,23.200000,...,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [46]:
X = df.drop(columns=["Appliances"])
y = df["Appliances"]

In [47]:
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [48]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [50]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
rmse = round(rmse, 3)
print("Root Mean Squared Error:", rmse)

Root Mean Squared Error: 93.64

In [49]:
mae = mean_absolute_error(y_test, y_pred)
mae = round(mae, 2)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 53.64

In [44]:
from sklearn.metrics import r2_score

# Assuming you have already trained your linear regression model and made predictions on the test set
r_squared = r2_score(y_test, y_pred)
r_squared = round(r_squared, 2)
print("Coefficient of Determination (R-squared):", r_squared)

Coefficient of Determination (R-squared): 0.15

In [32]:
X = df.drop(columns=["Appliances"])
y = df["Appliances"]

In [39]:
model = LinearRegression()
model.fit(X_scaled, y)
y_pred = model.predict(X_scaled)

In [36]:
rss = mean_squared_error(y, y_pred) * len(y)
rss = round(rss, 2)
print("Residual Sum of Squares (RSS):", rss)

Residual Sum of Squares (RSS): 177053871.04